---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dsp-hello-world-ingress
spec:
  rules:
  - host: developer-induction-shabe.notprod.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: dsp-hello-world-service
          servicePort: 80
        path: /
